version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
      - book_crossing_data:/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - data-importer
    environment:
      - POSTGRES_DB=mlapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./backend:/app

  # Serwis do pobierania i importowania danych
  data-downloader:
    build:
      context: ./database
      dockerfile: Dockerfile.importer
    volumes:
      - book_crossing_data:/data
    command: ["./download_data.sh"]
    
  data-importer:
    build:
      context: ./database
      dockerfile: Dockerfile.importer
    depends_on:
      - db
      - data-downloader
    environment:
      - POSTGRES_DB=mlapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - book_crossing_data:/data
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL...'
        while ! nc -z db 5432; do sleep 1; done
        echo 'PostgreSQL started'
        echo 'Starting data import...'
        python data_import.py
      "

volumes:
  postgres_data:
  book_crossing_data: